# DOBBY ALIASES (Auto-generated by Dobby installer)
# Do not edit manually - managed by installation script

# Main dobby command
alias dobby='__INSTALL_DIR__/scripts/dobby-control.sh'

# Convenience aliases
alias dobby-run='__INSTALL_DIR__/scripts/dobby-control.sh run'
alias dobby-stop='__INSTALL_DIR__/scripts/dobby-control.sh stop'
alias dobby-free='__INSTALL_DIR__/scripts/dobby-control.sh free'
alias dobby-restart='__INSTALL_DIR__/scripts/dobby-control.sh restart'
alias dobby-status='__INSTALL_DIR__/scripts/dobby-control.sh status'
alias dobby-attach='__INSTALL_DIR__/scripts/dobby-control.sh attach'
alias dobby-logs='__INSTALL_DIR__/scripts/dobby-control.sh logs'
alias dobby-update='__INSTALL_DIR__/scripts/dobby-control.sh update'
alias dobby-settings='__INSTALL_DIR__/scripts/dobby-control.sh settings'
alias dobby-help='__INSTALL_DIR__/scripts/dobby-control.sh help'
alias dobby-uninstall='__INSTALL_DIR__/scripts/dobby-control.sh uninstall'
