name: Quality Gate
on: push

jobs:
  Flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flake8
        run: |
          pip install flake8 flake8-isort
      - name: Run Flake8
        run: |
          flake8
  Mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"
      - uses: actions/checkout@v2
      - name: Install Deps
        run: |
          pip install -r requirements-dev.txt
      - name: Run Mypy
        run: |
          mypy .
