name: Quality Gate
on: push

jobs:
  Flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flake8
        run: |
          pip install flake8 flake8-isort
      - name: Run Flake8
        run: |
          flake8
