name: Quality Gate
on: push


jobs:
  Ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup
      - name: Run Ruff
        run: |
          ruff check .
  Vulture:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup
      - name: Run Vulture
        run: |
          vulture .

  Mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup
      - name: Run Mypy
        run: |
          mypy .

  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup
      - name: Run Tests
        run: |
          pytest --v .